# Generated by Django 5.1.5 on 2026-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIngestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramProductDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField(db_index=True)),
                ('photo_file_id', models.CharField(blank=True, max_length=255)),
                ('photo_url', models.URLField(blank=True)),
                ('raw_caption', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('chat_id', 'message_id')},
            },
        ),
    ]
