# Generated by Django 5.1.5 on 2026-02-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description_uk', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name_uk',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brand', models.CharField(db_index=True, max_length=128)),
                ('frame_size', models.CharField(db_index=True, max_length=64)),
                ('wheel_size', models.CharField(db_index=True, max_length=64)),
                ('frame_material', models.CharField(db_index=True, max_length=128)),
                ('brake_type', models.CharField(db_index=True, max_length=128)),
                ('fork_type', models.CharField(db_index=True, max_length=128)),
                ('gears', models.PositiveIntegerField(db_index=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], db_index=True, max_length=16)),
                ('availability', models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock')], db_index=True, max_length=16)),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ('-is_main', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'price'], name='catalog_pro_categor_5a4a66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'price'], name='catalog_pro_brand_7fb1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability', 'condition'], name='catalog_pro_availab_d7e072_idx'),
        ),
    ]
